inherited fPayrollMain: TfPayrollMain
  Caption = 'fPayrollMain'
  ClientHeight = 521
  ClientWidth = 861
  OnCreate = FormCreate
  ExplicitWidth = 877
  ExplicitHeight = 560
  PixelsPerInch = 96
  TextHeight = 14
  inherited pMaster: TJvPanel
    Width = 861
    Height = 521
    BorderWidth = 0
    ExplicitWidth = 861
    ExplicitHeight = 521
    object pcMain: TJvPageControl
      Left = 0
      Top = 0
      Width = 861
      Height = 521
      ActivePage = tsPayroll
      Align = alClient
      MultiLine = True
      TabOrder = 0
      ReduceMemoryUse = True
      object tsPayroll: TTabSheet
        Caption = 'Payroll'
        ImageIndex = 1
        object pResult: TJvPanel
          Left = 0
          Top = 35
          Width = 853
          Height = 457
          HotTrackFont.Charset = DEFAULT_CHARSET
          HotTrackFont.Color = clWindowText
          HotTrackFont.Height = -11
          HotTrackFont.Name = 'Tahoma'
          HotTrackFont.Style = []
          Align = alClient
          BevelOuter = bvNone
          ParentBackground = False
          TabOrder = 0
          object pGrid: TPanel
            Left = 0
            Top = 0
            Width = 853
            Height = 457
            Align = alClient
            BevelOuter = bvNone
            BorderWidth = 1
            TabOrder = 0
            object gList: TcxGrid
              Left = 1
              Top = 1
              Width = 851
              Height = 455
              Align = alClient
              TabOrder = 0
              LookAndFeel.Kind = lfFlat
              LookAndFeel.NativeStyle = False
              LookAndFeel.SkinName = 'DevExpressStyle'
              object vList: TcxGridDBTableView
                OnDblClick = vListDblClick
                Navigator.Buttons.CustomButtons = <>
                Navigator.Buttons.First.Visible = False
                Navigator.Buttons.PriorPage.Visible = False
                Navigator.Buttons.Prior.Visible = False
                Navigator.Buttons.Next.Visible = False
                Navigator.Buttons.NextPage.Visible = False
                Navigator.Buttons.Last.Visible = False
                Navigator.Buttons.Insert.Visible = False
                Navigator.Buttons.Append.ImageIndex = 1
                Navigator.Buttons.Delete.Visible = False
                Navigator.Buttons.Edit.Visible = False
                Navigator.Buttons.Refresh.Visible = False
                Navigator.Buttons.SaveBookmark.Visible = False
                Navigator.Buttons.GotoBookmark.Visible = False
                Navigator.Buttons.Filter.Visible = False
                OnCustomDrawCell = vListCustomDrawCell
                DataController.DataSource = dmPayroll.dscPayrollList
                DataController.Summary.DefaultGroupSummaryItems = <>
                DataController.Summary.FooterSummaryItems = <>
                DataController.Summary.SummaryGroups = <>
                OptionsBehavior.PostponedSynchronization = False
                OptionsBehavior.FocusCellOnTab = True
                OptionsBehavior.FocusFirstCellOnNewRecord = True
                OptionsBehavior.GoToNextCellOnEnter = True
                OptionsCustomize.ColumnFiltering = False
                OptionsCustomize.ColumnGrouping = False
                OptionsCustomize.ColumnHidingOnGrouping = False
                OptionsCustomize.ColumnHorzSizing = False
                OptionsCustomize.ColumnMoving = False
                OptionsData.Appending = True
                OptionsData.Deleting = False
                OptionsData.DeletingConfirmation = False
                OptionsSelection.CellSelect = False
                OptionsSelection.HideFocusRectOnExit = False
                OptionsSelection.InvertSelect = False
                OptionsSelection.UnselectFocusedRecordOnExit = False
                OptionsView.FocusRect = False
                OptionsView.NoDataToDisplayInfoText = 'No record found.'
                OptionsView.ScrollBars = ssVertical
                OptionsView.GroupByBox = False
                OptionsView.Indicator = True
                Styles.Selection = csSelectedRow
                object vListemployee_name: TcxGridDBColumn
                  Caption = 'Employee'
                  DataBinding.FieldName = 'employee_name'
                  MinWidth = 170
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 170
                end
                object vListsalary: TcxGridDBColumn
                  Caption = 'Salary'
                  DataBinding.FieldName = 'salary'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.Focusing = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
                object vListnumber_of_days: TcxGridDBColumn
                  Caption = 'Days'
                  DataBinding.FieldName = 'number_of_days'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '0.00'
                  MinWidth = 40
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 40
                end
                object vListleaves_with_pay: TcxGridDBColumn
                  Caption = 'LWP'
                  DataBinding.FieldName = 'lwp'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 55
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 55
                end
                object vListleaves_without_pay: TcxGridDBColumn
                  Caption = 'LWOP'
                  DataBinding.FieldName = 'lwop'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 55
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 55
                end
                object vListundertime: TcxGridDBColumn
                  Caption = 'U/T'
                  DataBinding.FieldName = 'ut'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 55
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 55
                end
                object vListgross: TcxGridDBColumn
                  Caption = 'Gross'
                  DataBinding.FieldName = 'gross'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
                object vListdeduction: TcxGridDBColumn
                  Caption = 'Deduction'
                  DataBinding.FieldName = 'deduction'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
                object vListallowance: TcxGridDBColumn
                  Caption = 'Allowance'
                  DataBinding.FieldName = 'allowance'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
                object vListadjustment: TcxGridDBColumn
                  Caption = 'Others'
                  DataBinding.FieldName = 'adjustment'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00;(###,##0.00)'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
                object vListnet: TcxGridDBColumn
                  Caption = 'Net'
                  DataBinding.FieldName = 'net'
                  PropertiesClassName = 'TcxCurrencyEditProperties'
                  Properties.DisplayFormat = '###,##0.00;(###,##0.00)'
                  MinWidth = 70
                  Options.Editing = False
                  Options.Filtering = False
                  Options.FilteringFilteredItemsList = False
                  Options.FilteringMRUItemsList = False
                  Options.FilteringPopup = False
                  Options.FilteringPopupMultiSelect = False
                  Options.IgnoreTimeForFiltering = False
                  Options.IncSearch = False
                  Options.GroupFooters = False
                  Options.Grouping = False
                  Options.HorzSizing = False
                  Options.Moving = False
                  Width = 70
                end
              end
              object lvlList: TcxGridLevel
                GridView = vList
              end
            end
          end
        end
        object pnlSearch: TPanel
          Left = 0
          Top = 0
          Width = 853
          Height = 35
          Align = alTop
          ParentBackground = False
          TabOrder = 1
          DesignSize = (
            853
            35)
          object Label1: TLabel
            Left = 16
            Top = 13
            Width = 53
            Height = 14
            Caption = 'Employee'
          end
          object edEmployeeSearch: TcxTextEdit
            Left = 78
            Top = 7
            Anchors = [akLeft, akTop, akRight, akBottom]
            Properties.OnChange = edEmployeeSearchPropertiesChange
            TabOrder = 0
            Width = 763
          end
        end
      end
    end
  end
  inherited ilBaseMain: TcxImageList
    FormatVersion = 1
    DesignInfo = 42992536
  end
  object csrPayroll: TcxStyleRepository
    Left = 56
    Top = 448
    PixelsPerInch = 96
    object csSelectedRow: TcxStyle
      AssignedValues = [svColor]
      Color = 16764315
    end
  end
end
